version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: client-ng-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: cd client-ng && npm install
      - run: cd client-ng && npm run lint --force
      - save_cache:
          key: client-ng-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: cd client-ng && npm run test:ci --
      - run: cd client-ng && npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
